services:
  postgres:
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgressecretpass
      POSTGRES_DB: cloudstorage
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    expose:
      - 1080
      - 1025

  # redis:
  #   image: redis:7-alpine
  #   expose:
  #     - 6379
