version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/clouddb
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/clouddb/

volumes:
  db:
